### ISSUE TITLE
ruleset does not work

### ISSUE THREAD

**Issue by floweywastaken** [Game4all/gamebosu#135]
i download it and i get this error
![image](https://user-images.githubusercontent.com/96350902/167314619-15d98e93-c044-4b8b-8a35-eb03fbcf0fc7.png)

**Comment by Game4all** [comment]
#133 / #136 should fix this.

**Comment by floweywastaken** [comment]
i accidentally upgraded to 509

**Comment by Game4all** [comment]
> i accidentally upgraded to 509
this is fine

**Comment by floweywastaken** [comment]
am i able to close this?

**Comment by Game4all** [comment]
Please wait for the new release dropping to do so 🛩️

**Comment by floweywastaken** [comment]
ok thx cause i am new to this

**Comment by floweywastaken** [comment]
it does
