### ISSUE TITLE
Make clicking in ROM selection work regardless of mouse activation settings during gameplay

### ISSUE THREAD

**Issue by Alextibtab** [Game4all/gamebosu#174]
![image](https://user-images.githubusercontent.com/48660540/194728573-3c028942-a4d3-40b5-9977-8707fdcbfefd.png)

Either I'm missing something simple or maybe my ROMs don't work but I can't click on them or get any kind of feedback I've pressed every single key on my keyboard nothing happens? Am I doing something wrong I just dragged the ROMs into the ROM folder and can't play them

**Comment by Game4all** [comment]
Try toggling on mouse clicks during gameplay (F10)

**Comment by Alextibtab** [comment]
Thanks that fixed it for me. Might be useful to add that somewhere in the README as when looking for a solution all the reddit comments just pointed to this repo and then the original poster would respond saying that didn't help them and I bet that's a common thing that would catch a lot of people out.

**Comment by Game4all** [comment]
I'll leave this open till I submit a commit fixing this up since I myself had this happen to me a few times while deving and I would like this to get fixed.

**Comment by Game4all** [comment]
Just released 2022.1010.0 which fixes this definitely.
