### ISSUE TITLE
rulesets could not load

### ISSUE THREAD

**Issue by 72888hshu** [Game4all/gamebosu#225]
![image](https://github.com/Game4all/gamebosu/assets/48046222/08a3127b-039e-4e88-a3af-e6eb66de45b4)

osu!lazer version: 2023.621.0-lazer
gamebosu version: current latest.

**Comment by Game4all** [comment]
thanks for the report! could you please provide logs files which should contain the reasons the ruleset failed to load as I am unable to reproduce the situation you're running into.

**Comment by 72888hshu** [comment]
[runtime.log](https://github.com/Game4all/gamebosu/files/11966601/runtime.log)

I guess its this log because I can find gamebosu related log only in this log.

**Comment by Game4all** [comment]
thanks for the lots! will investigate soon

**Comment by Game4all** [comment]
just uploaded a [new release](https://github.com/Game4all/gamebosu/releases/tag/2023.708.0) which should fix the problems encountered. please let me know if you encounter any error further.
