### ISSUE TITLE
rulesets still wont load

### ISSUE THREAD

**Issue by 72888hshu** [Game4all/gamebosu#226]
even after updating from last issue (#225), the rulesets still wont work in my lazer client. Perhaps its my environment problem?

osu!lazer version: 2023.621.0-lazer
gamebosu version: current latest (2023.708)

Error warning by osu!lazer:
![image](https://github.com/Game4all/gamebosu/assets/48046222/4a1c8523-f549-4468-aea0-706d4c9a2cb5)

Log File: 
[runtime.log](https://github.com/Game4all/gamebosu/files/11994960/runtime.log)

Basic system information:
OS: Windows 11 Pro
Version: 10.0.22621 Build 22621
System Manufacture: GIGABYTE
Processor:11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz, 2688 Mhz, 6 Core(s), 12 Logical Processor(s)
(Info get from "System Information" Windows executable.)

**Comment by Game4all** [comment]
Just released [2023.709](https://github.com/Game4all/gamebosu/releases/tag/2023.709.0) which fixes your issue this time. Turns out I forgor to update my build scripts 💀
